export const METHOD_ANNOTATIONS: Record<string, string> = {
  'identities.fetch': 'Fetches an identity by its 32-byte identifier from the Identity tree in GroveDB. The proof contains the merkle path from the root to this identity node.',
  'identities.balanceAndRevision': 'Reads the credit balance (1 DASH = 100 billion credits) and revision counter for an identity.',
  'identities.getKeys': 'Fetches all public keys associated with an identity. Keys control what the identity can sign.',
  'identities.nonce': 'Reads the identity nonce — a counter that prevents replay attacks on state transitions.',
  'identities.contractNonce': 'Reads the contract-specific nonce for an identity, used for document state transitions.',
  'identities.byPublicKeyHash': 'Resolves an identity by the hash of one of its public keys.',
  'identities.byNonUniquePublicKeyHash': 'Finds identities sharing a non-unique public key hash.',
  'contracts.fetch': 'Fetches a data contract by ID. Contracts define the schema for documents stored on Platform.',
  'contracts.getHistory': 'Fetches all historical revisions of a data contract, keyed by block height.',
  'documents.get': 'Fetches a single document by ID within a data contract and document type.',
  'documents.query': 'Executes a GroveDB query against a document type. Supports where clauses, ordering, limits, and pagination.',
  'tokens.totalSupply': 'Reads the total minted supply of a token.',
  'tokens.statuses': 'Fetches the current status (active, paused, frozen) for one or more tokens.',
  'tokens.directPurchasePrices': 'Reads the direct purchase price configuration for tokens.',
  'tokens.contractInfo': 'Resolves a token ID to its owning contract and position within that contract.',
  'tokens.identityBalances': 'Reads the balance of multiple tokens held by a single identity.',
  'addresses.get': 'Fetches Platform address info including nonce and credit balance.',
  'dpns.resolveName': 'Resolves a DPNS name to its owner identity ID. No proof variant available.',
  'dpns.username': 'Fetches the primary DPNS username for an identity.',
  'dpns.usernames': 'Fetches all DPNS usernames owned by an identity.',
  'dpns.getUsernameByName': 'Fetches detailed DPNS username info by name.',
  'dpns.isNameAvailable': 'Checks if a DPNS label is available for registration. No proof variant.',
  'dpns.isContestedUsername': 'Checks if a DPNS label triggers the contested name flow. No proof variant.',
  'dpns.isValidUsername': 'Validates a DPNS label against naming rules. No proof variant — runs locally.',
  'stateTransitions.waitForResult': 'Waits for a state transition to be included in a block. No proof variant.',
  'voting.contestedResourceIdentityVotes': 'Fetches how an identity voted on contested resources.',
  'voting.contestedResourceVoteState': 'Fetches the full vote state for a contested resource (contenders, votes, etc.).',
  'voting.votePollsByEndDate': 'Lists active vote polls filtered by end date range.',
  'group.identityGroups': 'Lists which groups an identity belongs to.',
  'group.groupsDataContracts': 'Fetches group definitions across multiple data contracts.',
  'group.contestedResources': 'Lists contested resources within a data contract.',
  'group.infos': 'Fetches group definitions for a data contract.',
  'group.info': 'Fetches a single group definition by contract and position.',
  'group.members': 'Lists members and their power for a group.',
  'group.actions': 'Lists pending or closed group actions (multi-sig proposals).',
  'epoch.current': 'Fetches the current epoch info (index, start time, core height, fee multiplier).',
  'epoch.epochsInfo': 'Fetches info for a range of epochs.',
  'epoch.finalizedInfos': 'Fetches finalized epoch info including protocol version used.',
  'epoch.evonodesProposedBlocksByRange': 'Counts blocks proposed by each evonode in an epoch.',
  'epoch.evonodesProposedBlocksByIds': 'Counts blocks proposed by specific evonodes in an epoch.',
  'system.status': 'Returns Platform chain status (block height, peers, version). No proof variant.',
  'system.currentQuorumsInfo': 'Returns current LLMQ quorum information. No proof variant.',
  'system.totalCreditsInPlatform': 'Reads total credits locked in Platform across all identities.',
  'system.prefundedSpecializedBalance': 'Reads a prefunded specialized balance for an identity.',
  'system.pathElements': 'Raw GroveDB key lookup — reads specific elements at a given tree path.',
  'protocol.versionUpgradeState': 'Reads the protocol version upgrade state (current and desired versions).',
  'protocol.versionUpgradeVoteStatus': 'Lists evonode votes for protocol version upgrades.',
};

export const PROOF_FIELD_ANNOTATIONS: Record<string, string> = {
  height: 'Platform chain block height at which this proof was generated.',
  epoch: 'Current epoch number. Epochs rotate masternode reward distribution roughly every ~18 hours.',
  coreChainLockedHeight: 'Highest ChainLock-confirmed Dash Core block height known to Platform.',
  protocolVersion: 'Active Platform protocol version number.',
  chainId: 'Short ASCII identifier for this Platform chain (e.g. "evo1" for mainnet).',
  timeMs: 'Block timestamp in milliseconds since Unix epoch.',
  quorumHash: 'Hash of the LLMQ quorum that signed this proof. Verifiable against the quorum public key on the Dash Core chain.',
  quorumType: 'LLMQ quorum type (e.g., 106 = platform quorum). Different quorum types have different sizes and thresholds.',
  signature: 'BLS threshold signature over the state root + block metadata. This is the core trust anchor — it proves the quorum attested to this state.',
  round: 'Tenderdash consensus round in which this block was finalized. Usually 0 for normal operation.',
  blockIdHash: 'Hash of the Platform block containing this state.',
  grovedbProof: 'Raw GroveDB merkle proof bytes. Cryptographically proves the queried value exists (or does not exist) in the authenticated state tree.',
};

export const OVERVIEW_TEXT =
  'Every query to Dash Platform can return a cryptographic proof. ' +
  'The proof contains a GroveDB merkle path (proving the data exists in the state tree) ' +
  'plus a BLS threshold signature from a quorum of masternodes (proving the state tree root is authentic). ' +
  'Together they let your browser independently verify that the data it received is genuine — ' +
  'no trust in any single server required.';
